name: motion_tsv_generator
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libsqlite=3.50.1
  - libstdcxx=15.1.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.3.0
  - openssl=3.5.0
  - pandas=2.3.0
  - pip=25.1.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - readline=8.2
  - six=1.17.0
  - tk=8.6.13
  - tzdata=2025b
